# Generated by Django 4.0.1 on 2022-01-10 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeamName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=100, null=True, verbose_name='Team Name')),
                ('age_group', models.CharField(choices=[('U7', 'U7'), ('U8', 'U8'), ('U9', 'U9'), ('U10', 'U10'), ('U11', 'U11'), ('U12', 'U12'), ('U13', 'U13'), ('U14', 'U14'), ('U15', 'U15'), ('U16', 'U16')], max_length=3, null=True)),
                ('venue', models.CharField(max_length=120, null=True, verbose_name='Venue')),
                ('address', models.CharField(max_length=200, null=True, verbose_name='Address')),
                ('contact', models.CharField(max_length=60, null=True, verbose_name='Contact Name')),
                ('contact_mob', models.CharField(max_length=15, null=True, verbose_name='Contact Mobile No')),
                ('contact_email', models.EmailField(max_length=200, null=True, verbose_name='Email')),
                ('map_link', models.URLField(max_length=300, null=True, verbose_name='Map Address Link')),
            ],
        ),
    ]
